export const facilities = [
  {
    id: '1',
    service_name: 'Southern Cross Care Parkes',
    physical_address: '2 Production St, Parkes NSW 2870',
    physical_suburb: 'Parkes',
    physical_state: 'NSW',
    physical_post_code: '2870',
    aged_care_planning_region: 'Central West',
    care_type: 'Residential',
    residential_places: 120,
    home_care_places: 0,
    restorative_care_places: 12,
    provider_name: 'Southern Cross Care',
    organisation_type: 'Religious Organisation',
    abs_remoteness: 'Outer Regional',
    availability_group: 'Likely Available',
    data_source: 'Demo data for CareLinked portfolio site',
    latitude: -33.1372,
    longitude: 148.1748,
    australian_government_funding: 13628407,
    overall_star_rating: 4,
    residents_experience_rating: 4,
    compliance_rating: 4,
    staffing_rating: 3,
    quality_measures_rating: 4,
    re_food_score: 0.82,
    re_safety_score: 0.86,
    re_respect_score: 0.88,
    re_caring_score: 0.9,
    re_home_score: 0.81,
    s_rn_care_minutes_target: 40,
    s_rn_care_minutes_actual: 38,
    s_total_care_minutes_target: 215,
    s_total_care_minutes_actual: 218,
    rn_minutes_met: false,
    total_minutes_met: true
  },
  {
    id: '2',
    service_name: 'Monash Gardens Aged Care',
    physical_address: '15 Beddoe Ave, Clayton VIC 3168',
    physical_suburb: 'Clayton',
    physical_state: 'VIC',
    physical_post_code: '3168',
    aged_care_planning_region: 'South East Melbourne',
    care_type: 'Residential',
    residential_places: 95,
    home_care_places: 0,
    restorative_care_places: 10,
    provider_name: 'Monash Gardens Group',
    organisation_type: 'Private Organisation',
    abs_remoteness: 'Major Cities',
    availability_group: 'Possibly Available',
    data_source: 'Demo data for CareLinked portfolio site',
    latitude: -37.9144,
    longitude: 145.1300,
    australian_government_funding: 8500000,
    overall_star_rating: 5,
    residents_experience_rating: 5,
    compliance_rating: 4,
    staffing_rating: 4,
    quality_measures_rating: 5,
    re_food_score: 0.9,
    re_safety_score: 0.89,
    re_respect_score: 0.93,
    re_caring_score: 0.92,
    re_home_score: 0.88,
    s_rn_care_minutes_target: 42,
    s_rn_care_minutes_actual: 45,
    s_total_care_minutes_target: 215,
    s_total_care_minutes_actual: 230,
    rn_minutes_met: true,
    total_minutes_met: true
  },
  {
    id: '4',
    service_name: 'Adelaide Community Support',
    physical_address: '45 Elder Rd, Adelaide SA 5000',
    physical_suburb: 'Adelaide',
    physical_state: 'SA',
    physical_post_code: '5000',
    aged_care_planning_region: 'Adelaide Metro',
    care_type: 'Multi-Purpose Service',
    residential_places: 80,
    home_care_places: 20,
    restorative_care_places: 8,
    provider_name: 'SA Health',
    organisation_type: 'Government',
    abs_remoteness: 'Major Cities',
    availability_group: 'Possibly Available',
    data_source: 'Demo data for CareLinked portfolio site',
    latitude: -34.9285,
    longitude: 138.6007,
    australian_government_funding: 7800000,
    overall_star_rating: 4,
    residents_experience_rating: 4,
    compliance_rating: 5,
    staffing_rating: 4,
    quality_measures_rating: 4
  },
  {
    id: '5',
    service_name: 'Perth Respite Care Centre',
    physical_address: '78 Wellness Ave, Perth WA 6000',
    physical_suburb: 'Perth',
    physical_state: 'WA',
    physical_post_code: '6000',
    aged_care_planning_region: 'Perth Metro',
    care_type: 'Transition Care',
    residential_places: 70,
    home_care_places: 0,
    restorative_care_places: 18,
    provider_name: 'WA Care Group',
    organisation_type: 'Private Organisation',
    abs_remoteness: 'Major Cities',
    availability_group: 'Likely Available',
    data_source: 'Demo data for CareLinked portfolio site',
    latitude: -31.9523,
    longitude: 115.8613,
    australian_government_funding: 10200000,
    overall_star_rating: 4,
    residents_experience_rating: 4,
    compliance_rating: 4,
    staffing_rating: 4,
    quality_measures_rating: 3
  },
  {
    id: '6',
    service_name: 'Tasmania Dementia Care',
    physical_address: '23 River St, Hobart TAS 7000',
    physical_suburb: 'Hobart',
    physical_state: 'TAS',
    physical_post_code: '7000',
    aged_care_planning_region: 'Tasmania South',
    care_type: 'Short-Term Restorative Care (STRC)',
    residential_places: 55,
    home_care_places: 0,
    restorative_care_places: 16,
    provider_name: 'TasCare',
    organisation_type: 'Non-Profit Organisation',
    abs_remoteness: 'Inner Regional',
    availability_group: 'Highly Constrained',
    data_source: 'Demo data for CareLinked portfolio site',
    latitude: -42.8821,
    longitude: 147.3272,
    australian_government_funding: 4500000,
    overall_star_rating: 3,
    residents_experience_rating: 4,
    compliance_rating: 3,
    staffing_rating: 3,
    quality_measures_rating: 3
  },
  {
    id: '7',
    service_name: 'Sydney Residential Care Hub',
    physical_address: '101 Harbour St, Sydney NSW 2000',
    physical_suburb: 'Sydney',
    physical_state: 'NSW',
    physical_post_code: '2000',
    aged_care_planning_region: 'Sydney Metro',
    care_type: 'Residential',
    residential_places: 140,
    home_care_places: 0,
    restorative_care_places: 20,
    provider_name: 'Sydney Living Group',
    organisation_type: 'Private Organisation',
    abs_remoteness: 'Major Cities',
    availability_group: 'Likely Available',
    data_source: 'Demo data for CareLinked portfolio site',
    latitude: -33.8688,
    longitude: 151.2093,
    australian_government_funding: 15000000,
    overall_star_rating: 5,
    residents_experience_rating: 5,
    compliance_rating: 5,
    staffing_rating: 4,
    quality_measures_rating: 5
  },
  {
    id: '9',
    service_name: 'Gold Coast Memory Support',
    physical_address: '55 Ocean Dr, Gold Coast QLD 4217',
    physical_suburb: 'Gold Coast',
    physical_state: 'QLD',
    physical_post_code: '4217',
    aged_care_planning_region: 'Gold Coast',
    care_type: 'National Aboriginal and Torres Strait Islander Aged Care Program',
    residential_places: 100,
    home_care_places: 30,
    restorative_care_places: 8,
    provider_name: 'Wellness Group',
    organisation_type: 'Private Organisation',
    abs_remoteness: 'Major Cities',
    availability_group: 'Possibly Available',
    data_source: 'Demo data for CareLinked portfolio site',
    latitude: -28.0167,
    longitude: 153.4000,
    australian_government_funding: 9800000,
    overall_star_rating: 4,
    residents_experience_rating: 4,
    compliance_rating: 4,
    staffing_rating: 4,
    quality_measures_rating: 4
  },
  {
    id: '10',
    service_name: 'Melbourne CHSP Support Centre',
    physical_address: '88 Collins St, Melbourne VIC 3000',
    physical_suburb: 'Melbourne',
    physical_state: 'VIC',
    physical_post_code: '3000',
    aged_care_planning_region: 'Melbourne Metro',
    care_type: 'Residential',
    residential_places: 85,
    home_care_places: 18,
    restorative_care_places: 8,
    provider_name: 'Victoria Community Care',
    organisation_type: 'Government',
    abs_remoteness: 'Major Cities',
    availability_group: 'Constrained by Market',
    data_source: 'Demo data for CareLinked portfolio site',
    latitude: -37.8136,
    longitude: 144.9631,
    australian_government_funding: 11200000,
    overall_star_rating: 4,
    residents_experience_rating: 3,
    compliance_rating: 4,
    staffing_rating: 3,
    quality_measures_rating: 4
  }
]
