export default [
  {
    id: 1,
    name: 'Southern Cross Care Parkes',
    image: 'https://images.unsplash.com/photo-1580281658629-1c5c9fef0c5a?auto=format&fit=crop&w=1200&q=80',
    address: '2 Production St, Parkes NSW 2870',
    suburb: 'Parkes',
    state: 'New South Wales',
    postcode: '2870',
    careType: 'Residential Care',
    organisationType: 'Government Funded (CHSP/HCP)',
    funding: '$13,628,407',
    bedAvailability: 'Low',
    totalBeds: 120,
    provider: 'Southern Cross Care',
    providerType: 'Religious Organisation',
    remoteness: 'Outer Regional',
    acpr: 'Central West',
    distance: 8
  },
  {
    id: 2,
    name: 'Monash Gardens Aged Care',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    address: '15 Beddoe Ave, Clayton VIC 3168',
    suburb: 'Clayton',
    state: 'Victoria',
    postcode: '3168',
    careType: 'Residential Care',
    organisationType: 'Private / Self-funded',
    funding: '$8,500,000',
    bedAvailability: 'High',
    totalBeds: 95,
    provider: 'Monash Gardens Group',
    providerType: 'Private Organisation',
    remoteness: 'Major Cities',
    acpr: 'South East Melbourne',
    distance: 5
  },
  {
    id: 3,
    name: 'Brisbane Home Care Services',
    image: 'https://images.unsplash.com/photo-1576765608866-5b51046452be?auto=format&fit=crop&w=1200&q=80',
    address: '22 Care Rd, Brisbane QLD 4000',
    suburb: 'Brisbane',
    state: 'Queensland',
    postcode: '4000',
    careType: 'Home Care Package (HCP)',
    organisationType: 'Government Funded (CHSP/HCP)',
    funding: '$6,200,000',
    bedAvailability: 'Medium',
    totalBeds: 60,
    provider: 'BlueCare',
    providerType: 'Non-Profit Organisation',
    remoteness: 'Major Cities',
    acpr: 'Brisbane North',
    distance: 12
  },
  {
    id: 4,
    name: 'Adelaide Community Support',
    image: 'https://images.unsplash.com/photo-1599423300746-b62533397364?auto=format&fit=crop&w=1200&q=80',
    address: '45 Elder Rd, Adelaide SA 5000',
    suburb: 'Adelaide',
    state: 'South Australia',
    postcode: '5000',
    careType: 'CHSP - Community Support',
    organisationType: 'Government Funded (CHSP/HCP)',
    funding: '$7,800,000',
    bedAvailability: 'Low',
    totalBeds: 80,
    provider: 'SA Health',
    providerType: 'Government',
    remoteness: 'Major Cities',
    acpr: 'Adelaide Metro',
    distance: 20
  },
  {
    id: 5,
    name: 'Perth Respite Care Centre',
    image: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=80',
    address: '78 Wellness Ave, Perth WA 6000',
    suburb: 'Perth',
    state: 'Western Australia',
    postcode: '6000',
    careType: 'Respite Care',
    organisationType: 'Private / Self-funded',
    funding: '$10,200,000',
    bedAvailability: 'High',
    totalBeds: 70,
    provider: 'WA Care Group',
    providerType: 'Private Organisation',
    remoteness: 'Major Cities',
    acpr: 'Perth Metro',
    distance: 3
  },
  {
    id: 6,
    name: 'Tasmania Dementia Care',
    image: 'https://images.unsplash.com/photo-1599420186946-7b5d7d9d8b9f?auto=format&fit=crop&w=1200&q=80',
    address: '23 River St, Hobart TAS 7000',
    suburb: 'Hobart',
    state: 'Tasmania',
    postcode: '7000',
    careType: 'Memory Care',
    organisationType: 'DVA (Veterans)',
    funding: '$4,500,000',
    bedAvailability: 'Medium',
    totalBeds: 55,
    provider: 'TasCare',
    providerType: 'Non-Profit Organisation',
    remoteness: 'Inner Regional',
    acpr: 'Tasmania South',
    distance: 15
  },
  {
    id: 7,
    name: 'Sydney Residential Care Hub',
    image: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200&q=80',
    address: '101 Harbour St, Sydney NSW 2000',
    suburb: 'Sydney',
    state: 'New South Wales',
    postcode: '2000',
    careType: 'Residential Care',
    organisationType: 'Private / Self-funded',
    funding: '$15,000,000',
    bedAvailability: 'High',
    totalBeds: 140,
    provider: 'Sydney Living Group',
    providerType: 'Private Organisation',
    remoteness: 'Major Cities',
    acpr: 'Sydney Metro',
    distance: 2
  },
  {
    id: 8,
    name: 'Canberra Home Care Package',
    image: 'https://images.unsplash.com/photo-1598228723793-52759bba239c?auto=format&fit=crop&w=1200&q=80',
    address: '33 Capital Ave, Canberra ACT 2600',
    suburb: 'Canberra',
    state: 'ACT',
    postcode: '2600',
    careType: 'Home Care Package (HCP)',
    organisationType: 'Government Funded (CHSP/HCP)',
    funding: '$5,700,000',
    bedAvailability: 'Medium',
    totalBeds: 75,
    provider: 'ACT Health',
    providerType: 'Government',
    remoteness: 'Major Cities',
    acpr: 'ACT Region',
    distance: 9
  },
  {
    id: 9,
    name: 'Gold Coast Memory Support',
    image: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
    address: '55 Ocean Dr, Gold Coast QLD 4217',
    suburb: 'Gold Coast',
    state: 'Queensland',
    postcode: '4217',
    careType: 'Memory Care',
    organisationType: 'Private / Self-funded',
    funding: '$9,800,000',
    bedAvailability: 'High',
    totalBeds: 100,
    provider: 'Wellness Group',
    providerType: 'Private Organisation',
    remoteness: 'Major Cities',
    acpr: 'Gold Coast',
    distance: 6
  },
  {
    id: 10,
    name: 'Melbourne CHSP Support Centre',
    image: 'https://images.unsplash.com/photo-1599423300746-b62533397364?auto=format&fit=crop&w=1200&q=80',
    address: '88 Collins St, Melbourne VIC 3000',
    suburb: 'Melbourne',
    state: 'Victoria',
    postcode: '3000',
    careType: 'CHSP - Community Support',
    organisationType: 'Government Funded (CHSP/HCP)',
    funding: '$11,200,000',
    bedAvailability: 'Low',
    totalBeds: 85,
    provider: 'Victoria Community Care',
    providerType: 'Government',
    remoteness: 'Major Cities',
    acpr: 'Melbourne Metro',
    distance: 4
  }
]